# INTRODUCTION

# Say "Hello, World!" With Python

In [4]:
if __name__ == '__main__':
    print("Hello, World!")

Hello, World!


# Python If-Else

In [6]:
#!/bin/python
import math
import os
import random
import re
import sys
if __name__ == '__main__':
    n = int(input().strip())
if n%2 == 1:
    print('Weird')
elif n >= 2 and n <= 5:
    print('Not Weird')
elif n >= 6 and n <= 20:
    print('Weird')
else:
    print('Not Weird')

3
Weird


# Arithmetic Operators

In [7]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

3
2
5
1
6


# Python: Division

In [8]:
from __future__ import division
if __name__ == '__main__':
    a = int(input())
    b = int(input())
print(a//b)
print(a/b)

4
3
1
1.3333333333333333


# Loops

In [9]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i**2)

5
0
1
4
9
16


# Write a function

In [10]:
def is_leap(year):
    leap = False
    return leap
year = int(input())
print(is_leap(year))

1990
False


# Print Function

In [12]:
from __future__ import print_function
if __name__ == '__main__':
    n = int(input())
for i in range(n):
    print(i+1, end='')

3
123

# Basic Data Types

# List Comprehensions

In [13]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    l = [[a, b, c] for a in range(x+1) for b in range(y+1) for c in range(z+1) if a+b+c != n]
    print(l)

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


# Find the Runner-Up Score!

In [14]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    a = sorted(list(set(arr)))
    print(a[-2])

5
2 3 6 6 5
5


# Nested Lists

In [15]:
if __name__ == '__main__':
    l = []
    names = []
    scores = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        l.append([name, score])
        scores.append(score)
    scores = set(scores)
    for i in l:
        if i[1] == sorted(scores)[1]:
            names.append(i[0])
    names = sorted(names)
    for i in names:
        print(i)

4 
Prashant 
32 
Pallavi 
36 
Dheeraj 
39 
Shivam 
40
Pallavi 


# Finding the percentage

In [17]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        line = input().split()
        name, scores = line[0], line[1:]
        scores = map(float, scores)
        student_marks[name] = scores
    query_name = input()
    for i in student_marks:
        if i == query_name:
            print(format(sum(student_marks[i])/len(str(student_marks[i])), ".2f"))
            break

3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60 
Malika
4.94


# Lists

In [19]:
if __name__ == '__main__':
    N = int(input())
    a = []
    for i in range(N):
        s = input()
        if s.split()[0] == "append":
            a.append(int(s.split()[1]))
        elif s.split()[0] == "insert":
            a.insert(int(s.split()[1]), int(s.split()[2]))
        elif s.split()[0] == "remove":
            a.remove(int(s.split()[1]))
        elif s.split()[0] == "print":
            print(a)
        elif s.split()[0] == "sort":
            a.sort()
        elif s.split()[0] == "reverse":
            a.reverse()
        elif s.split()[0] == "pop":
            a.pop()

12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


# Tuples

In [20]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t = tuple(integer_list)
    print(hash(t))

2
1 2
-3550055125485641917


# Strings

# sWAP cASE

In [25]:
def swap_case(s):
    l = ''
    for i in s:
        if i.lower() == i:
            l = l + i.upper()
        else:
            l = l + i.lower()
    return l

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


# String Split and Join

In [23]:
def split_and_join(line):
    s = line.split(" ")
    z = ''
    for i in s:
        z = z + i + "-"
    z = z[:-1]
    return z

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

this is a string
this-is-a-string


# What's Your Name?

In [26]:
def print_full_name(first, last):
    s = "Hello " + first + " " + last + "! You just delved into python."
    print(s)

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Ross 
Taylor
Hello Ross  Taylor! You just delved into python.


# Mutations

In [28]:
def mutate_string(string, position, character):
    string = string[:position] + character + string[position+1:]
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 k
abrackdabra


# Find a string

In [29]:
def count_substring(string, sub_string):
    count = 0
    for i in range(len(string)-len(sub_string)+1):
        if string[i] == sub_string[0]:
            b = True
            for j in range(len(sub_string)):
                if string[i+j] != sub_string[j]:
                    b = False
                    break
            if b:
                count += 1
    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


# String Validators

In [30]:
if __name__ == '__main__':
    s = input()
    an, al, n, l, u = 'False', 'False', 'False', 'False', 'False'
    for i in s:
        if i.isalnum():
            an = 'True'
        if i.isalpha():
            al = 'True'
        if i.isdigit():
            n = 'True'
        if i.islower():
            l = 'True'
        if i.isupper():
            u = 'True'
    print(an)
    print(al)
    print(n)
    print(l)
    print(u)

qA2
True
True
True
True
True


# Text Wrap

In [32]:
import textwrap

def wrap(string, max_width):
    s = ''
    for i in range(len(string)):
        if i%max_width == 0 and i != 0:
            s = s + "\n"
        s = s + string[i]
    return s

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

ABCDEFGHIJKLIMNOQRSTUVWXYZ
4
ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


# String Formatting

In [33]:
def print_formatted(number):
    w = number.bit_length()
    for i in range(1, number+1):
        print(f'{i:{w}d} {i:{w}o} {i:{w}X} {i:{w}b}')

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

2
 1  1  1  1
 2  2  2 10


# Capitalize!

In [103]:
#!/bin/python3
import math
import os
import random
import re
import sys

def solve(s):
    s2 = s[0].upper()
    for i in range(0, len(s)-1):
        if s[i] == ' ':
            c = s[i+1].upper()
        else:
            c = s[i+1]
        s2 = s2 + c
    return s2

if __name__ == '__main__':
    s = input()
    result = solve(s)
    print(result)

chris alan
Chris Alan


# Sets

# Introduction to Sets

In [36]:
def average(array):
    return sum(set(array))/len(set(array))

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


# Symmetric Difference

In [38]:
n = input()
a = input().split()
m = input()
b = input().split()
a = set(list(map(int, a)))
b = set(list(map(int, b)))
s = sorted(list(set(a.difference(b).union(b.difference(a)))))
for i in s:
    print(i)

4
2 4 5 9
4
2 4 11 12
5
9
11
12


# No Idea!

In [39]:
n, m = input().split()
arr = input().split()
a = input().split()
b = input().split()
arr = list(map(int, arr))
a = set(list(map(int, a)))
b = set(list(map(int, b)))
print(sum([(i in a) - (i in b) for i in arr]))

3 2
1 5 3
3 1
5 7
1


# Set .add()

In [40]:
n = int(input())
country = []
for i in range(n):
    country.append(input())
country = set(country)
print(len(country))

7
UK
China
USA
France
New Zealand
UK
France
5


# Set .discard(), .remove() & .pop()

In [41]:
n = int(input())
s = set(map(int, input().split()))
m = int(input())
for i in range(m):
    c = input()
    if c.split()[0] == "pop":
        s.pop()
    elif c.split()[0] == "discard":
        s.discard(int(c.split()[1]))
    elif c.split()[0] == "remove":
        s.remove(int(c.split()[1]))
print(sum(s))

9
1 2 3 4 5 6 7 8 9
10
pop
remove 9 
discard 9 
discard 8 
remove 7 
pop 
discard 6
remove 5 
pop 
discard 5
4


# Set .union() Operation

In [42]:
n = int(input())
a = set(list(map(int, set(input().split()))))
m = int(input())
b = set(list(map(int, set(input().split()))))
c = a.union(b)
print(len(c))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


# Set .intersection() Operation

In [43]:
n = int(input())
a = set(list(map(int, set(input().split()))))
m = int(input())
b = set(list(map(int, set(input().split()))))
c = a.intersection(b)
print(len(c))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


# Set .difference() Operation

In [44]:
n = int(input())
a = set(list(map(int, set(input().split()))))
m = int(input())
b = set(list(map(int, set(input().split()))))
c = a.difference(b)
print(len(c))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


# Set .symmetric_difference() Operation

In [45]:
n = int(input())
a = set(list(map(int, set(input().split()))))
m = int(input())
b = set(list(map(int, set(input().split()))))
c = a.symmetric_difference(b)
print(len(c))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


# Set Mutations

In [46]:
n = int(input())
s = set(map(int, input().split()))
m = int(input())
for i in range(m):
    c = input()
    if c.split()[0] == "update":
        t = set(map(int, input().split()))
        s.update(t)
    elif c.split()[0] == "intersection_update":
        t = set(map(int, input().split()))
        s.intersection_update(t)
    elif c.split()[0] == "difference_update":
        t = set(map(int, input().split()))
        s.difference_update(t)
    elif c.split()[0] == "symmetric_difference_update":
        t = set(map(int, input().split()))
        s.symmetric_difference_update(t)
print(sum(s))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10 
2 3 5 6 8 9 1 4 7 11 
update 2 
55 66 
symmetric_difference_update 5 
22 7 35 62 58 
difference_update 7 
11 22 35 55 58 62 66
38


# The Captain's Room

In [47]:
k = int(input())
arr = list(map(int, input().split()))
s = set(arr)
a = sum(s)*k-sum(arr)
print(int(a/(k-1)))

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


# Check Subset

In [48]:
T = int(input())
for i in range(T):
    n = int(input())
    a = set(map(int, input().split()))
    m = int(input())
    b = set(map(int, input().split()))
    if b.intersection(a) == a:
        print('True')
    else:
        print('False')

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


# Check Strict Superset

In [104]:
a = set(map(int, input().split()))
n = int(input())
b = True
for i in range(n):
    c = set(map(int, input().split()))
    if a.intersection(c) != c or len(a) == len(c):
        b = False
        break
print(b)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


# Collections

# collections.Counter()

In [50]:
from collections import Counter
x = int(input())
sizes = Counter(map(int, input().split()))
n = int(input())
money = 0
for i in range(n):
    s, p = map(int, input().split())
    if s in sizes and sizes[s] > 0:
        money += p
        sizes[s] -= 1
print(money)

10
2 3 4 5 6 8 7 6 5 18
6 
6 55
6 45
6 55
4 40
18 60
10 50
200


# DefaultDict Tutorial

In [51]:
n, m = map(int, input().split())
a, b = [], []
for i in range(n):
    a.append(input())
for i in range(m):
    b.append(input())
for i in range(len(b)):
    count = 0
    for j in range(len(a)):
        if b[i] == a[j]:
            print(j+1, end=' ')
            count += 1
    if count == 0:
        print(-1, end='')
    print()

5 2
a
a
b
a
b
a
b
1 2 4 
3 5 


# Collections.namedtuple()

In [53]:
from collections import namedtuple
n = int(input())
Student = namedtuple('Student', input().split())
s = 0
for i in range(n):
    a, b, c, d = input().split()
    s = s + int(Student(a, b, c, d).MARKS)
print(s/n)

5
ID         MARKS      NAME       CLASS
1          97         Raymond    7
2          50         Steven     4
3          91         Adrian     9
4          72         Stewart    5
5          80         Peter      6
78.0


# Collections.OrderedDict()

In [54]:
from collections import OrderedDict
n = int(input())
d = OrderedDict()
for i in range(n):
    a = input().split()
    b = " ".join(a[:-1])
    if b in d:
        d[b] += int(a[-1])
    else:
        d[b] = int(a[-1])
for i in d:
    print(i, d[i])

9
BANANA FRIES 12
POTATO CHIPS 30
APPLE JUICE 10
CANDY 5
APPLE JUICE 10
CANDY 5
CANDY 5
CANDY 5
POTATO CHIPS 30
BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


# Collections.deque()

In [55]:
from collections import deque
d = deque()
n = int(input())
for i in range(n):
    s = input().split()
    if s[0] == "pop":
        d.pop()
    elif s[0] == "append":
        d.append(int(s[1]))
    elif s[0] == "popleft":
        d.popleft()
    elif s[0] == "appendleft":
        d.appendleft(int(s[1]))
for i in d:
    print(i, end=' ')

6
append 1 
append 2 
append 3 
appendleft 4 
pop 
popleft
1 2 

# Numpy

# Arrays

In [56]:
import numpy

def arrays(arr):
    arr.reverse()
    a = numpy.array(arr, float)
    return a

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Shape and Reshape

In [57]:
import numpy as np
arr = list(map(int,input().split()))
a = np.array(arr)
print(np.reshape(a, (3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten

In [58]:
import numpy as np
n,m = input().split()
arr = []
for i in range(int(n)):
    s = input().split()
    for j in s:
        arr.append(int(j))
print(np.reshape(np.array(arr), (int(n),int(m))).T)
print(np.array(arr))

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Concatenate

In [59]:
import numpy as np
x = input().split()
n, m, p = int(x[0]), int(x[1]), int(x[2])
a = []
for i in range(n):
    s = input().split()
    for j in s:
        a.append(int(j))
b = []
for i in range(m):
    s = input().split()
    for j in s:
        b.append(int(j))
a = np.array(a).reshape(n,p)
b = np.array(b).reshape(m,p)
print(np.concatenate((a, b)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Zeros and Ones

In [60]:
import numpy as np
x = input().split()
print(np.zeros(list(map(int,x)), dtype=np.int))
print(np.ones(list(map(int,x)), dtype=np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and Identity

In [61]:
import numpy as np
np.set_printoptions(legacy='1.13')
n, m = input().split()
print(np.eye(int(n), int(m)))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array Mathematics

In [62]:
import numpy as np
n, m = map(int, input().split())
a = []
b = []
for i in range(n):
    a.append(input().split())
for i in range(n):
    b.append(input().split())
a = np.array(a, dtype=int)
b = np.array(b, dtype=int)
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Floor, Ceil and Rint

In [63]:
import numpy as np
np.set_printoptions(sign=' ')
a = np.array(input().split(), float)
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Sum and Prod

In [64]:
import numpy as np
np.set_printoptions(sign=' ')
n, m = map(int, input().split())
a = []
for i in range(n):
    a.append(input().split())
a = np.array(a, int)
print(np.prod(np.sum(a, axis = 0), axis = 0))

2 2
1 2
3 4
24


# Min and Max

In [65]:
import numpy as np
np.set_printoptions(sign=' ')
n, m = map(int, input().split())
a = []
for i in range(n):
    a.append(input().split())
a = np.array(a, int)
print(np.max(np.min(a, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


# Mean, Var, and Std

In [66]:
import numpy as np
n, m = map(int, input().split())
a = []
for i in range(n):
    a.append(input().split())
a = np.array(a, int)
print(np.mean(a, axis = 1))
print(np.var(a, axis = 0))
print(np.around(np.std(a),decimals=11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Dot and Cross

In [67]:
import numpy as np
n = int(input())
a = []
b = []
for i in range(n):
    a.append(input().split())
for i in range(n):
    b.append(input().split())
a = np.array(a, int)
b = np.array(b, int)
print(np.dot(a,b))

2 
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Inner and Outer

In [68]:
import numpy as np
a = np.array(input().split(), int)
b = np.array(input().split(), int)
print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


# Polynomials

In [70]:
import numpy as np
a = list(map(float, input().split()))
x = int(input())
print(np.polyval(a, x))

1.1 2 3
0
3.0


# Linear Algebra

In [71]:
import numpy as np
np.set_printoptions(legacy='1.13')
n = int(input())
a = []
for i in range(n):
    a.append(input().split())
a = np.array(a, float)
print(np.linalg.det(a))

2
1.1 1.1
1.1 1.1
0.0


# Date and Time

# Calendar Module

In [72]:
import calendar
d = list(map(int, input().split()))
wd = calendar.weekday(d[2], d[0], d[1])
print(calendar.day_name[wd].upper())

08 05 2015
WEDNESDAY


# Time Delta

In [75]:
#!/bin/python3
import math
import os
import random
import re
import sys
import datetime as dt

def time_delta(t1, t2):
    a = dt.datetime.strptime(t1, '%a %d %b %Y %H:%M:%S %z')
    b = dt.datetime.strptime(t2, '%a %d %b %Y %H:%M:%S %z')
    c = (a-b).total_seconds()
    return(str(int(abs(c))))

if __name__ == '__main__':
    t = int(input())
    for t_itr in range(t):
        t1 = input()
        t2 = input()
        delta = time_delta(t1, t2)
        print(delta)

2
Sun 10 May 2015 13:54:36 -0700
Sun 10 May 2015 13:54:36 -0000
25200
Sat 02 May 2015 19:54:36 +0530
Fri 01 May 2015 13:54:36 -0000
88200


# Errors and Exceptions

# Exceptions

In [76]:
t = int(input())
for i in range(t):
    try:
        a, b = input().split()
        print(int(a)//int(b))
    except Exception as e:
        print("Error Code:",e)

3
1 0
Error Code: integer division or modulo by zero
2 $
Error Code: invalid literal for int() with base 10: '$'
3 1
3


# Built-Ins

# Zipped!

In [77]:
N, X = map(int, input().split())
a = []
for i in range(X):
    a.append(list(map(float,input().split())))
for i in zip(*a): 
    print(sum(i)/len(i))

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


# Athlete Sort

In [78]:
#!/bin/python3
import math
import os
import random
import re
import sys

if __name__ == '__main__':
    nm = input().split()
    n = int(nm[0])
    m = int(nm[1])
    arr = []
    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))
    k = int(input())
arr.sort(key=lambda x:x[k])
for i in arr:
    print(*i)

5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


# ginortS

In [79]:
s = input()
low = []
up = []
odd = []
even = []
for i in s:
    if i.isalpha() and i.islower():
        low.append(i)
    elif i.isalpha() and i.isupper():
        up.append(i)
    elif i.isnumeric() and int(i)%2 == 1:
        odd.append(i)
    else:
        even.append(i)
print(str(''.join(sorted(low))) + str(''.join(sorted(up))) + str(''.join(sorted(odd))) + str(''.join(sorted(even))))

Sorting1234
ginortS1324


# Python Functionals

# Map and Lambda Function

In [80]:
cube = lambda x: x**3

def fibonacci(n):
    if n == 0:
        return []
    if n == 1:
        return [0]
    a, b = 0, 1
    c = [a, b]
    for i in range(n-2):
        a = a+b
        c.append(a)
        a,b = b,a
    return c

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


# XML

# XML 1 - Find the Score

In [82]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    return len(node.attrib) + sum(get_attr_number(i) for i in node)

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

ParseError: no element found: line 1, column 0 (<string>)

# Closures and Decorators

# Standardize Mobile Number Using Decorators

In [83]:
def wrapper(f):
    def fun(l):
        x = []
        for i in range(len(l)):
            if len(l[i]) == 10:
                x.append('+91 ' + l[i][0:5] + ' ' + l[i][5:])
            elif l[i][0] == '0':
                x.append('+91 ' + l[i][1:6] + ' ' + l[i][6:])
            elif l[i][0] == '9':
                x.append('+91 ' + l[i][2:7] + ' ' + l[i][7:])
            else:
                x.append(l[i][0:3] + ' ' + l[i][3:8] + ' ' + l[i][8:])
        print(*sorted(x), sep='\n')
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130 
919875641230 
9195969878
+91 78954 62130 
+91 91959 69878
+91 98756 41230 


# Decorators 2 - Name Directory

In [85]:
import operator

def person_lister(f):
    def inner(people):
        x = []
        y = people[0][2]
        order = []
        for i in range(len(people)-1):
            for j in range(len(people)-1):
                if int(people[j][2]) > int(people[j+1][2]):
                    people[j], people[j+1] = people[j+1], people[j]
        for i in people:
            if i[-1] == 'M':
                x.append('Mr. ' + i[0] + ' ' + i[1])
            else:
                x.append('Ms. ' + i[0] + ' ' + i[1])
        return x
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M 
Robert Bustle 32 M 
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


# Regex and Parsing

# Detect Floating Point Number



In [86]:
t = int(input())
for i in range(t):
    try:
        a = input()
        if float(a):
            print("True")
        else:
            print("False")
    except:
        print("False")

4
4.0O0 
False
-1.00 
True
+4.54 
True
SomeRandomStuff
False


# Re.split()

In [88]:
regex_pattern = r"[,.]"	# Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


# Group(), Groups() & Groupdict()

In [89]:
import re
s = input()
x = re.search(r"([a-z0-9])\1+", s)
if x:
    print(x.group(1))
else:
    print(-1)

12345678910111213141516171820212223
1


# Re.findall() & Re.finditer()

In [90]:
import re
s = input()
a = re.findall('[aeiouAEIOU]{2,}[^aeiouAEIOU]{1}', s)
if a:
    for i in a:
        print(i[:-1])
else:
    print("-1")

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


# Re.start() & Re.end()

In [98]:
import re
s = input()
k = input()
m = re.search(k, s)
if m == None:
    print('(-1, -1)')
else:
    pattern = re.compile(k)
    while m:
        print('(' + str(m.start()) + ', ' + str(m.end()-1) + ')')
        m = pattern.search(s, m.start()+1)

aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


# Validating phone numbers

In [99]:
n = int(input())
for i in range(n):
    s = input()
    if s.isnumeric() and len(s) == 10 and s[0] in ['7', '8', '9']:
        print('YES')
    else:
        print('NO')

2
9587456281
YES
1252478965
NO


# Validating and Parsing Email Addresses

In [100]:
import re
n = int(input())
for i in range(n):
    s = input().split()
    m = re.match(r'<[A-Za-z](\w|-|\.|_)+@[A-Za-z]+\.[A-Za-z]{1,3}>', s[1])
    if m:
        print(*s)

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


# Problem 2

# Birthday Cake Candles

In [91]:
#!/bin/python3
import math
import os
import random
import re
import sys

def birthdayCakeCandles(candles):
    return candles.count(max(candles))

if __name__ == '__main__':
    candles_count = int(input().strip())
    candles = list(map(int, input().rstrip().split()))
    result = birthdayCakeCandles(candles)
    print(str(result)

4
3 2 1 3
2


# Number Line Jumps

In [92]:
#!/bin/python3
import math
import os
import random
import re
import sys

def kangaroo(x1, v1, x2, v2):
    if x1 == x2:
        return 'YES'
    elif x1 < x2 and v1 < v2:
        return 'NO'
    elif x1 > x2 and v1 > v2:
        return 'NO'
    elif x1 != x2 and v1 == v2:
        return 'NO'
    elif x1 < x2:
        x = 1
    else:
        x = 2
    for i in range(1, 10000):
        x1 = x1 + v1
        x2 = x2 + v2
        if x1 == x2:
            return 'YES'
            break
        if x == 1 and x1 > x2:
            return 'NO'
        elif x == 2 and x2 > x1:
            return 'NO'

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()
    x1 = int(first_multiple_input[0])
    v1 = int(first_multiple_input[1])
    x2 = int(first_multiple_input[2])
    v2 = int(first_multiple_input[3])
    result = kangaroo(x1, v1, x2, v2)
    print(result)

0 3 4 2
YES


# Viral Advertising

In [93]:
#!/bin/python3
import math
import os
import random
import re
import sys
def viralAdvertising(n):
    s = 5
    l = math.floor(s/2)
    c = l
    for i in range(n-1):
        s = 3*l
        l = math.floor(s/2)
        c += l
    return c

if __name__ == '__main__':
    n = int(input().strip())
    result = viralAdvertising(n)
    print(str(result))

3
9


# Recursive Digit Sum

In [95]:
#!/bin/python3
import math
import os
import random
import re
import sys

def superDigit(n, k):
    if len(n) == 1:
        return int(n)
    return superDigit(str(sum(list(map(int, str(n))))*k), 1)

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()
    n = first_multiple_input[0]
    k = int(first_multiple_input[1])
    result = superDigit(n, k)
    print(str(result))

148 3
3


# Insertion Sort - Part 1

In [96]:
#!/bin/python3
import math
import os
import random
import re
import sys

def insertionSort1(n, arr):
    x = arr[-1]
    i = n-2
    while i >= 0:
        if x < arr[i]:
            arr[i+1] = arr[i]
        else:
            arr[i+1] = arr[i]
            arr[i+1] = x
            print(*arr)
            break
        print(*arr)
        i -= 1
        if i < 0:
            arr[0] = x
            print(*arr)

if __name__ == '__main__':
    n = int(input().strip())
    arr = list(map(int, input().rstrip().split()))
    insertionSort1(n, arr)

5
2 4 6 8 3
2 4 6 8 8
2 4 6 6 8
2 4 4 6 8
2 3 4 6 8


# Insertion Sort - Part 2

In [97]:
#!/bin/python3
import math
import os
import random
import re
import sys

def insertionSort2(n, arr):
    for j in range(1, n):
        x = arr[j]
        i = j-1
        while i >= 0:
            if x < arr[i]:
                arr[i+1] = arr[i]
            else:
                arr[i+1] = arr[i]
                arr[i+1] = x
                break
            i -= 1
            if i < 0:
                arr[0] = x
        print(*arr)

if __name__ == '__main__':
    n = int(input().strip())
    arr = list(map(int, input().rstrip().split()))
    insertionSort2(n, arr)

6
1 4 3 5 6 2
1 4 3 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 2 3 4 5 6
